### ISSUE TITLE
NameError: name 'cwd' is not defined

### ISSUE THREAD

**Issue by yuanyehome** [collinskatie/checkmate#2]
Hi, when I run the demo, I got "NameError: name 'cwd' is not defined". Here is the error log:
```
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/Users/yuanye/opt/anaconda3/envs/openai/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/yuanye/opt/anaconda3/envs/openai/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/yuanye/opt/anaconda3/envs/openai/lib/python3.8/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/Users/yuanye/opt/anaconda3/envs/openai/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/Users/yuanye/opt/anaconda3/envs/openai/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/yuanye/opt/anaconda3/envs/openai/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/yuanye/opt/anaconda3/envs/openai/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/Users/yuanye/opt/anaconda3/envs/openai/lib/python3.8/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "/Users/yuanye/opt/anaconda3/envs/openai/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/Users/yuanye/opt/anaconda3/envs/openai/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/yuanye/checkmate/experiment.py", line 550, in <module>
    if "collins" in cwd:
NameError: name 'cwd' is not defined
```

It seems the code uses an undefined variable.
<img width="946" alt="图片" src="https://github.com/collinskatie/checkmate/assets/36473484/701cc160-b6cc-489a-a99f-077e44edd59f">

**Comment by albertqjiang** [comment]
This is intentional. You should specify the cwd and the unique_saving_path to suit your file system :)
